#!/bin/bash

cd /tmp 

echo 'Installing mongo_backup'

echo 'Downloading mongo_backup.conf to /etc/mongo_backup.conf'

if [[ -f /etc/mongo_backup.conf ]]; then
	echo 'ERROR: Donut overwrite /etc/mongo_backup.conf'; exit

curl -fsSL https://raw.githubusercontent.com/mhenrixon/mongo_backup/master/mongo_backup.conf | sudo tee /etc/mongo_backup.conf
echo 'Downloading mongo_backup.sh to /usr/bin/mongo_backup'
curl -fsSL https://raw.githubusercontent.com/mhenrixon/mongo_backup/master/mongo_backup.sh | sudo tee /usr/bin/mongo_backup

echo 'Making /usr/bin/mongo_backup executable'
chmod +x /usr/bin/mongo_backup

echo 'Installation done, please modify /etc/mongo_backup.conf to match your needs'
